spring.application.name=firstapp

server.port=8081

server.servlet.context-path=/api

loggin.level.root=INFO
loggin.level.com.example.firstapp=DEBUG

spring.http.encoding.charset=UTF-8
spring.http,encoding.enabled=true